apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-image
spec:
  params:
    - name: repo_url
      type: string
    - name: revision
      type: string
    - name: gitops_repo_url
      type: string
  tasks:
    - name: code-clone
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      params:
        - name: URL
          value: $(params.repo_url)
        - name: REVISION
          value: $(params.revision)
        - name: SUBDIRECTORY
          value: source-code
      workspaces:
        - name: output
          workspace: shared-workspace


    - name: code-linting
      runAfter:
        - code-clone
      taskRef:
        name: placeholder
      params:
      - name: taskname
        value: code-linting

    - name: maven-package
      runAfter:
        - code-linting
      taskRef:
        name: maven-build
      params:
      - name: MAVEN_ARGS
        value: clean package -DskipTests
      - name: CONTEXT_DIR
        value: source-code
      workspaces:
        - name: source
          workspace: shared-workspace  

    - name: unit-tests
      runAfter:
        - maven-package
      taskRef:
        name: maven-build
      params:
      - name: MAVEN_ARGS
        value: clean install
      - name: CONTEXT_DIR
        value: source-code
      workspaces:
        - name: source
          workspace: shared-workspace  

    - name: build-image
      runAfter:
        - unit-tests
      taskRef:
        name: maven-build
      params:
      - name: MAVEN_ARGS
        value: compile jib:build
      - name: CONTEXT_DIR
        value: source-code
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: gitops-clone
      runAfter:
        - build-image
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      params:
        - name: URL
          value: $(params.gitops_repo_url)
        - name: REVISION
          value: main
        - name: SUBDIRECTORY
          value: "gitops"
      workspaces:
        - name: output
          workspace: shared-workspace
    
    - name: gitops-dev-deploy
      runAfter:
        -  gitops-clone
      taskRef:
        name: gitops-deploy
      params:
        - name: VERSION
          value: "$(tasks.build-image.results.VERSION)"
        - name: ENVIRONMENT
          value: dev
        - name: APP_NAME
          value: helloworld
      workspaces:
        - name: source
          workspace: shared-workspace

  workspaces:
    - name: shared-workspace
  results:
    - name: VERSION
      description: Version of the application
      value: "$(tasks.build-image.results.VERSION)"